# Generated by Django 3.1.13 on 2021-09-04 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avatar', '0002_auto_20210904_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfttemplate',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='images',
            name='raretiy',
            field=models.IntegerField(default=0),
        ),
    ]
