# Generated by Django 3.1.13 on 2021-11-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0003_auto_20210904_0744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nfttemplate',
            old_name='image',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='order',
        ),
        migrations.AddField(
            model_name='sections',
            name='sort_order',
            field=models.IntegerField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='nfttemplate',
            name='variants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nfttemplate',
            name='variants_used',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
