# Generated by Django 3.1.13 on 2021-11-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0004_auto_20211107_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfttemplate',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nfttemplate',
            name='title',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='nfttemplate',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
