# Generated by Django 3.1.13 on 2021-11-07 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0005_auto_20211107_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfttemplate',
            name='user',
        ),
    ]
