# Generated by Django 3.1.13 on 2021-11-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0008_sections_nft_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
