# Generated by Django 3.1.13 on 2021-11-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0009_auto_20211112_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sections',
            options={'ordering': ('-sort_order',)},
        ),
        migrations.AddField(
            model_name='images',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
