# Generated by Django 3.1.13 on 2021-11-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0010_auto_20211112_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='position_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='position_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
