# Generated by Django 3.1.13 on 2021-11-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0011_auto_20211113_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfttemplate',
            name='file',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
