# Generated by Django 3.1.13 on 2021-11-19 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0012_auto_20211113_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sections',
            options={'ordering': ('sort_order',)},
        ),
    ]
