# Generated by Django 3.1.13 on 2021-11-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0014_arrpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
