# Generated by Django 3.1.13 on 2021-11-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0015_images_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
