# Generated by Django 3.1.13 on 2021-11-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0018_auto_20211122_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ('sort_order',)},
        ),
        migrations.AlterField(
            model_name='arrpart',
            name='arr',
            field=models.CharField(max_length=50000, unique=True),
        ),
    ]
